version: '3.8'

services:
  # Public entrypoint (frontend / grounding API)
  url-parser:
    image: paulandrewfarrow/tollbit-url-parser:latest
    ports:
      - "80:5173"                       # Azure external port 80 → internal 5173
    environment:
      - NODE_ENV=production
      - PORT=5173
      - CORS_ORIGINS=https://monetizeplusappcompose.azurewebsites.net
    depends_on:
      - licensing-api
    networks:
      - tollbit-network

  # Optional Nginx edge gateway (kept internal for now)
  edge:
    image: nginx:alpine
    depends_on:
      - edge-worker
    networks:
      - tollbit-network

  # Edge worker – bot detection / routing
  edge-worker:
    image: paulandrewfarrow/tollbit-edge-worker:latest
    environment:
      - NODE_ENV=development
      - LICENSING_API_URL=http://licensing-api:3000
      - PUBLISHER_A_URL=http://publisher-a:8081
      - PUBLISHER_B_URL=http://publisher-b:8082
      - REDIS_URL=redis://redis:6379
    depends_on:
      - licensing-api
      - redis
    networks:
      - tollbit-network

  # Licensing API – authentication, tokens, metering
  licensing-api:
    image: paulandrewfarrow/tollbit-licensing-api:latest
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://tollbit:tollbit123@postgres:5432/tollbit
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-secret-key-change-in-production
      - JWT_ISSUER=gatehouse-licensing
      - JWT_AUDIENCE=gatehouse-edge
    depends_on:
      - postgres
      - redis
    networks:
      - tollbit-network

  # Publisher mocks
  publisher-a:
    image: paulandrewfarrow/tollbit-publisher-a:latest
    networks:
      - tollbit-network

  publisher-b:
    image: paulandrewfarrow/tollbit-publisher-b:latest
    networks:
      - tollbit-network

  # Publisher dashboard (internal UI)
  publisher-dashboard:
    image: paulandrewfarrow/tollbit-publisher-dashboard:latest
    depends_on:
      - licensing-api
    networks:
      - tollbit-network

  # Negotiation Agent – AI-to-AI license negotiation
  negotiation-agent:
    image: paulandrewfarrow/paulbit:latest
    environment:
      - NODE_ENV=production
      - PORT=3003
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=tollbit
      - POSTGRES_USER=tollbit
      - POSTGRES_PASSWORD=tollbit123
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_LEVEL=info
      - START_MCP=false
    depends_on:
      - postgres
      - redis
      - licensing-api
    networks:
      - tollbit-network

  # Databases / cache
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=tollbit
      - POSTGRES_USER=tollbit
      - POSTGRES_PASSWORD=tollbit123
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - tollbit-network

  redis:
    image: redis:7-alpine
    networks:
      - tollbit-network

networks:
  tollbit-network:

volumes:
  postgres-data:
