version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: monetizeplus
      POSTGRES_PASSWORD: monetizeplus123
      POSTGRES_DB: monetizeplus
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monetizeplus"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Licensing API - authentication, tokens, metering, policies
  licensing-api:
    image: paulandrewfarrow/monetizeplus-licensing-api:latest
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://monetizeplus:monetizeplus123@127.0.0.1:5432/monetizeplus
      REDIS_ENABLED: "false"
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: monetizeplus
      JWT_AUDIENCE: monetizeplus-edge
    ports:
      - "3000:3000"

  # URL-to-Markdown Parser
  urlparser:
    image: paulandrewfarrow/monetizeplus-url-parser:latest
    ports:
      - "8080:80"

  # Publisher Dashboard
  publisher-dashboard:
    image: paulandrewfarrow/monetizeplus-publisher-dashboard:latest
    depends_on:
      - licensing-api
    ports:
      - "80:80"
    environment:
      LICENSING_API_URL: http://127.0.0.1:3000
