version: '3'

services:
  urlparser:
    image: paulandrewfarrow/tollbit-url-parser:latest
    ports:
      - "80:5173"
    environment:
      NODE_ENV: production
      PORT: 5173
      CORS_ORIGINS: https://monetizeplusapp.azurewebsites.net
