version: '3'
services:
  licensing-api:
    image: paulandrewfarrow/tollbit-licensing-api:latest
    ports:
      - "3000:3000"
  urlparser:
    image: paulandrewfarrow/tollbit-url-parser:latest
    ports:
      - "80:80"
