version: "3.8"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: monetizeplus
      POSTGRES_PASSWORD: monetizeplus123
      POSTGRES_DB: monetizeplus
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    restart: always

  licensing-api:
    image: paulandrewfarrow/monetizeplus-licensing-api:latest
    depends_on:
      - postgres
      - redis
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgres://monetizeplus:monetizeplus123@postgres:5432/monetizeplus
      REDIS_URL: redis://redis:6379
      JWT_SECRET: super-secret-change-in-production
      JWT_ISSUER: monetizeplus
      JWT_AUDIENCE: monetizeplus-edge
    ports:
      - "3000:3000"

  edge-worker:
    image: paulandrewfarrow/monetizeplus-edge-worker:latest
    depends_on:
      - licensing-api
      - redis
    environment:
      NODE_ENV: production
      LICENSING_API_URL: http://licensing-api:3000
      REDIS_URL: redis://redis:6379
    ports:
      - "3001:3001"

  publisher-dashboard:
    image: paulandrewfarrow/monetizeplus-publisher-dashboard:latest
    depends_on:
      - licensing-api
      - edge-worker
    environment:
      NODE_ENV: production
      API_URL: http://licensing-api:3000
      EDGE_URL: http://edge-worker:3001
    ports:
      - "80:80"

volumes:
  pgdata:
