version: '3.8'

services:
  edge:
    image: nginx:alpine
    ports:
      - "80:8080"
    depends_on:
      - edge-worker
    networks:
      - tollbit-network
    command: >
      /bin/sh -c "cat > /etc/nginx/nginx.conf <<'EOF'
      worker_processes auto;
      events { worker_connections 1024; }

      http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        sendfile        on;
        keepalive_timeout  65;

        server {
          listen 8080;
          server_name _;

          location / {
            proxy_pass http://edge-worker:3000;
            proxy_set_header Host \$host;
            proxy_set_header X-Real-IP \$remote_addr;
            proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto \$scheme;
          }
        }
      }
      EOF
      && nginx -g 'daemon off;'"
      
  edge-worker:
    image: paulandrewfarrow/tollbit-edge-worker:latest
    environment:
      - NODE_ENV=development
      - LICENSING_API_URL=http://licensing-api:3000
      - PUBLISHER_A_URL=http://publisher-a:8081
      - PUBLISHER_B_URL=http://publisher-b:8082
      - REDIS_URL=redis://redis:6379
    depends_on:
      - licensing-api
      - redis
    networks:
      - tollbit-network

  licensing-api:
    image: paulandrewfarrow/tollbit-licensing-api:latest
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://tollbit:tollbit123@postgres:5432/tollbit
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-secret-key-change-in-production
      - JWT_ISSUER=gatehouse-licensing
      - JWT_AUDIENCE=gatehouse-edge
    depends_on:
      - postgres
      - redis
    networks:
      - tollbit-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=tollbit
      - POSTGRES_USER=tollbit
      - POSTGRES_PASSWORD=tollbit123
    networks:
      - tollbit-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    networks:
      - tollbit-network

networks:
  tollbit-network:

volumes:
  postgres-data:
